GET http://localhost:8081/api/todos

###

GET http://localhost:8081/api/todos/1

###

GET http://localhost:8081/api/todos/11231

###

POST http://localhost:8081/api/todos
Content-Type: application/json

{
  "task": "eat dinner",
  "isCompleted": false
}

### 

POST http://localhost:8081/api/todos
Content-Type: application/json


###

PUT http://localhost:8081/api/todos/1
Content-Type: application/json

{
  "task": "go take a shower",
  "isCompleted": true
}

### 

DELETE http://localhost:8081/api/todos/1

